### ISSUE TITLE
Next day with only times

### ISSUE THREAD

**Issue by KrunchMuffin** [jonthornton/Datepair.js#100]
Is there  a way you can find out if the time range overlaps to next day when only using times? 
say something like 7pm (sept 20) - 2am (sept 21)

**Comment by jonthornton** [comment]
Datepair.js doesn't have anything built in to help with this, but you could do it by comparing the times:
```javascript
if ($('#startTime').timepicker('getTime') > $('#endTime').timepicker('getTime')) {
  // the time range overlaps midnight
}
```
