### ISSUE TITLE
Duration not updated when changing time using setTime

### ISSUE THREAD

**Issue by mayankaggarwal092** [jonthornton/Datepair.js#102]
When you change the value  of start time and end time using the setTime method of timepicker, the duration is not updated. Instead we see duration that correspond to earlier start time.

**Comment by jonthornton** [comment]
Datepair is triggered by the `change` event. You can cause the duration update by firing a synthetic event after calling `setTime`. With jQuery, you'd do something like this:

```javascript
$('#someTimeInput').timepicker('setTime', new Date()).trigger('change')
```
