### ISSUE TITLE
Bower being discontinued

### ISSUE THREAD

**Issue by saleem-git** [jonthornton/Datepair.js#103]
Hi,

Since Bower is being discontinued, I would suggest adding the yarn as the package manager.

yarn add datepair.js

Or even npm

npm install datepair.js

The reason I ask this is because I started receiving error messages and warnings and had to migrate the bower modules to yarn on prod. We can avoid this hassle by simply using yarn (or even npm) from the start. The same is true for timepicker as well.

**Comment by jonthornton** [comment]
Thanks!
