### ISSUE TITLE
404, There isn't a GitHub Pages site here.

### ISSUE THREAD

**Issue by TLKG** [jonthornton/Datepair.js#106]
Clicked on the demo and source button go err 404 msg. Here is the URL, tried both .io and .com resulting the same:
http://jonthornton.github.com/Datepair.js

**Comment by cosky5** [comment]
Same problem with mine page too:
https://cosky5.github.io/Colour-GuessingGame/

**Comment by cosky5** [comment]
Open the repository and check out the settings and edit "Custom Domain" and save it
You can also check this link:
https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/

**Comment by kingsleykbc** [comment]
kingsleykbc.github.io

**Comment by Xulazz** [comment]
.
