### ISSUE TITLE
How do I make it not possible to select dates before the current one?

### ISSUE THREAD

**Issue by jonathanoh1** [jonthornton/Datepair.js#107]
How do I make it not possible to select dates before the current one?

im using this : 
" $('#start_date').on('change', function() {
  var start_date = $('#start_date').datepicker('getDate');
  var now = new Date();
  if (start_date < new Date()) {
    console.log(start_date, now);
  }
});
"
but I hope there is a function that does it in a simple option in $ ('# dateEvent .date'). datepicker ({/ * here * / });

thanks

**Comment by jonthornton** [comment]
I'm not sure I understand the functionality you're trying to achieve. Can you give an example?

**Comment by jonathanoh1** [comment]
in the datepicker of the month, if today is March 8, I want it impossible to select March 7 or days before, is there an option to disable those days?

**Comment by jonthornton** [comment]
No, you'll need to code that up manually.
