### ISSUE TITLE
Setting the date value programmatically  after initialisation

### ISSUE THREAD

**Issue by rlegge** [jonthornton/Datepair.js#120]
Hi,  Im using this Datepair, but i'm struggling to set the date and time value programmatically after its been initialised.  I can set each of the containers with a string value, but it doesn't save correctly. Im assuming I should be setting it to a JavaScript date object, but cant work out the syntax to do so correctly

Do you have an example of setting the date and time on a the datepair on a separate event?

Many Thanks..
Richard

**Comment by jonthornton** [comment]
Hi Richard, you'll want to use the `refresh` method, like this:

```javascript
$('#someInput').val(someValue) // this can be a string
 datepair.refresh();
```

As long as the way you're setting the date/time is supported by the date/time pickers you're using, Datepair's `refresh` method will make sure pairing logic works correctly.
