### ISSUE TITLE
Online documentation is broken due to TimePicker

### ISSUE THREAD

**Issue by Mibou** [jonthornton/Datepair.js#123]
Hello,

http://www.jonthornton.com/Datepair.js/

Is broken due to

https://jonthornton.github.io/jquery-timepicker/jquery.timepicker.js

being moved to

http://www.jonthornton.com/jquery-timepicker/dist/jquery.timepicker.js

and

http://www.jonthornton.com/jquery-timepicker/jquery.timepicker.css

being moved to

http://www.jonthornton.com/jquery-timepicker/dist/jquery.timepicker.css

**Comment by jonthornton** [comment]
Thanks for the heads up!
