### ISSUE TITLE
Does not trigger range events when changing time

### ISSUE THREAD

**Issue by espen** [jonthornton/Datepair.js#127]
How to reproduce:

1. Go to events example at https://www.jonthornton.com/Datepair.js/

2. Choose start date. 'Valid range selected' is triggered.

3. Set 2:00am as start time. No event is triggered.

4. Set 3:30am as end time.  No event is triggered.

5. Remove end time. 'Incomplete range' is triggered.

6. Set 3:30am as end time.  No event is triggered.

7. Go to end date and select the same date as before. 'Valid range selected' is triggered.

When changing date valid range event is always triggered. Not when changing time.

**Comment by interu** [comment]
Me too.

When I changed start time, couldn't call `updateTime` .

**Comment by espen** [comment]
I haven't tested but I think this is caused by this issue: https://github.com/jonthornton/Datepair.js/issues/128#issuecomment-757516726

**Comment by jonthornton** [comment]
@espen you're correct, there was an event bubbling bug in jquery.timepicker jonthornton/jquery-timepicker@0873fe4

This should be fixed now.
