### ISSUE TITLE
time  picker

### ISSUE THREAD

**Issue by ramakanth0011** [jonthornton/Datepair.js#133]
thank you soo much sir. really apricate your work and support....
one more think i want to add in the start end and end time.
like suppose current time is 3.48pm . i want the start time start from 4:00 pm.
can u please help me with this...
thanks alot sir

**Comment by jonthornton** [comment]
Try 

```
$('#theStartTime).timepicker({
  forceRoundTime: true
});
```

**Comment by ramakanth0011** [comment]
din not work in my case sir, how can i contact you sir?

$('#basicExample .time').timepicker({        
        'showDuration': true,
        // forceRoundTime: true,
        'timeFormat': 'g:ia'
    });
