### ISSUE TITLE
defaultTimeDelta not working

### ISSUE THREAD

**Issue by luki-zz** [jonthornton/Datepair.js#142]
Hello, 
So I have following option: 
`jQuery("#datepicker").datetimepicker({
    defaultTimeDelta: 900000,
  });`
and expect my time to display in intervals of 15 min, but nothing changes.
As well how can I change my language to Polish?

**Comment by jonthornton** [comment]
Hi, I think you may be looking for https://github.com/xdan/datetimepicker. I'm not the maintainer of that project.
