### ISSUE TITLE
Is there a way to disable 0 mins?

### ISSUE THREAD

**Issue by triodo** [jonthornton/Datepair.js#36]

**Comment by jonthornton** [comment]
I don't understand. Could you explain more?

**Comment by triodo** [comment]
In the “time end” I have a duration with 30 min step, I want to disable 0 min.
I choose "time start" 2:00 and I want the "time end" to always be more than 2:00 so that I can not choose 0 min. (2:30; 3:00; 3:30 ...)

**Comment by triodo** [comment]
Did you understand what I write?

**Comment by jonthornton** [comment]
Datepair doesn't implement this kind of functionality, but you can do it reactively with an event handler.

```javascript
var datepair = new Datepair(....);
$('#someDatepair').on('rangeSelected', function(){
    if (datepair.getTimeDiff() <= 0) {
        // alert user, adjust values, etc
    }
});
