### ISSUE TITLE
The datepair changes the dates in a wrong way if I set the last hour with 23:59 value.

### ISSUE THREAD

**Issue by AdailtonSouza** [jonthornton/Datepair.js#37]
The datepair changes the dates in a wrong way if I set the last hour with 23:59 value.
Example:
- set the first day with 2015/03/04
- the second day automatically is set to 2015/03/04.
- set the first hour to 23:30 (or 11:00pm) the second time is set to 00:30 (or 12:30am) and the second day is set to 2015/03/05.
- changes the second date to 2015/03/04 and changes the second hour to 23:59 (or 11:59pm).
- after this the both date are set to 2015/03/03.

**Comment by tersariolli** [comment]
I am facing the same issue.

**Comment by cpestilli** [comment]
I had the same issue. Any fix ?

**Comment by jonthornton** [comment]
Noted :) I'll investigate this week.
