### ISSUE TITLE
end time getting bumped 24hrs

### ISSUE THREAD

**Issue by KrunchMuffin** [jonthornton/Datepair.js#38]
Here is the fiddle
http://jsfiddle.net/fv9m5my0/5/

select a date.
select a start time, say 9:00am
check end time, will show ok, don't select
go back to start time and select a time later than previous start time, say 10:00am
check end time. will be bumped all way up by 24hrs.

seems to work ok if defaultTimeDelta has a value other than null.

**Comment by jonthornton** [comment]
It was actually a bug in the timepicker plugin - a very subtle bug. Nice find. Thanks for posting a report.
