### ISSUE TITLE
exmaple with jquery UTC bug

### ISSUE THREAD

**Issue by vipconsult** [jonthornton/Datepair.js#40]
the exmaple with overwriting the update funciton doesn't take into account the UTC 

I think it should be: 

updateDate: function (el, v) {
            var utc = new Date();
            v.setMilliseconds(v.getMilliseconds()-(utc.getTimezoneOffset()* 60000))
            $(el).datepicker('setDate',v);
}

**Comment by jonthornton** [comment]
Can you demonstrate how this results in an error?

**Comment by vipconsult** [comment]
Here is an example:

https://jsfiddle.net/bg9pxut2/

the second input is always one day behind

and here is a short video what happens 
http://screencast.com/t/n9fz6XF7

**Comment by jonthornton** [comment]
You're overriding the `parseDate` function in your example and introducing some sort of UTC based offset - that's what's causing the error. This isn't a Datepair bug.

**Comment by vipconsult** [comment]
my point here was that in your Readme the example shows this code which is not right

https://github.com/jonthornton/Datepair.js/blob/master/README.md

**Comment by jonthornton** [comment]
The code in the jsFiddle you provided is different from the readme example.

**Comment by vipconsult** [comment]
how about this one:
https://jsfiddle.net/4hckgkxb/

**Comment by jonthornton** [comment]
I thought you were talking about the examples on [this page](http://jonthornton.github.io/Datepair.js/) - I'm sorry. You're right about the bug. I've updated the example.
