### ISSUE TITLE
NaN/NaN/NaN

### ISSUE THREAD

**Issue by jerrido** [jonthornton/Datepair.js#42]
Hi Jon,

Following this sequence of events will turn the end date field to NaN/NaN/NaN.  This behavior occurs in Datepair.js version 0.4.7, but *not* 0.4.6.

1. Visit Datepair.js demo.  (Firefox here)
2. Fill in all fields.  (Basic Example or jQuery Example)
3. Delete value in the start date field.
4. Change value in the end date field.
5. Change value in the start date field.

**Comment by jonthornton** [comment]
Thanks for pointing that out. Should be fixed now.
