### ISSUE TITLE
Overlapping time ranges over those disabled

### ISSUE THREAD

**Issue by andriuhatm** [jonthornton/Datepair.js#45]
For example, if i have defaultTimeDelta set to 3 hours and i choose a start time before the disabled period, the end time goes over the disabled period.

Example: 
'disableTimeRanges': [ [ 8:00, 9:00 ], [ 11:00, 13:00 ] ]

I don't have to be able to select 10:00 because the timeDelta is 3 hours. How to disable 3 hour period before second time range?
And there might be more keys in array, because the disabled time period is returned from Google Calendar API..
Thx..

**Comment by jonthornton** [comment]
You'll need to set `disableTimeRanges` on both the start and end pickers, with `timeDelta` as the offset between the two.

**Comment by andriuhatm** [comment]
Thank you.
I did this in a different way- i just subtract current "defaultTimeDelta" from all start times and then created a new array.
