### ISSUE TITLE
Get rid of AM/PM

### ISSUE THREAD

**Issue by JessNielsen** [jonthornton/Datepair.js#47]
is there a way to change the format of the time field, and perhaps the interval? Same goes for date - any way to change the format, that is when not using a datepicker but just the dropdown?

**Comment by jonthornton** [comment]
Yup! Datepair.js doesn't initialize date or time picket widgets - the developer has to code that themselves - so you can customize it to your heart's content. Initializing the date and time pickers is included the the examples for convenience. Please refer to the docs for your date and time picker plugins. (Though I'm the developer of both Datepair.js and jquery.timepicker, they're entirely independent projects.)
