### ISSUE TITLE
Setting anchor = null allows invalid time periods

### ISSUE THREAD

**Issue by jhegeman** [jonthornton/Datepair.js#52]
Hi Jon,

First of all a big thank-you for this nice plugin! I think the below is a bug, or maybe I'm just doing something wrong.

The problem can be reproduced with the bottom 'Anchor example' of the documentation:
  http://jonthornton.github.io/Datepair.js/
With the anchor set to null, the begin and end dates are still kept in the correct order: end date after begin date. When selecting a begin date after the currently-set end date, the end date will be moved to match the new begin date. This is not the case for the times. So it will not allow one to select an end date before the begin date, but when the dates are equal, it does allow one to select an end time before the begin time, resulting in an impossible time period.

Cheers,
Jeroen

**Comment by jonthornton** [comment]
Nice catch! Thanks for the detailed bug report.

**Comment by jhegeman** [comment]
Thanks Jon, but now, ahum, this had a side-effect. It looks as if it does not take into account the date when 'fixing' the time.

To reproduce (using the bottom example again):
- Select null anchor.
- Select begin date 10/25/2015. This will also set the end date to this date.
- Select begin time 1:00am. This will set the end time, in this case to 2:00am.
- Change begin date to 10/24/2015. Nothing else changes. (Correct.)
- Change begin time to 3:00am. Now the end time also changes to 3:00am, which is not correct.

I think it should only adjust the times in case the dates are equal.

Jeroen
