### ISSUE TITLE
Error on recent release

### ISSUE THREAD

**Issue by KrunchMuffin** [jonthornton/Datepair.js#53]
TypeError: (intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value) is not a function

File datepair.js line 322 col 1 in [anonymous]

**Comment by jonthornton** [comment]
Can you post instructions on how to reproduce the error?

**Comment by KrunchMuffin** [comment]
No, but usually denotes missing semicolons.

U have missing semicolon on lines 12,89,191,339

not that this would cause it, but
lines 223,226,267,271,275,276,298,302 have duplicate declaration with var

I'll fix those and try it out.

**Comment by jonthornton** [comment]
Thanks for the heads up on missing semicolons!
