### ISSUE TITLE
Start time set to end time when passing midnight

### ISSUE THREAD

**Issue by low** [jonthornton/Datepair.js#56]
Thanks for this script, Jon. It looks like I can scrap a lot of custom stuff from my version and adopt this. :)

So, to reproduce this minor issue (can also be seen on the current demo page):

- Select any start date (end date is now the same date);
- Select 10:00pm as start time (end time is now 11:00pm);
- Select 2:00am as end time, duration 4 hours.

The end date is now one day after the start date, which is what I expected.
However, the start time is now *also* 2:00am, when should remain at 10:00pm.

**Comment by jonthornton** [comment]
Thanks for the bug report!
