### ISSUE TITLE
How set time end?

### ISSUE THREAD

**Issue by jeffersongouveia** [jonthornton/Datepair.js#60]
Hello everyone, i set start time normally, but i need set time end too. Or set interval of 1 hour and display on input time end.

**Comment by jonthornton** [comment]
I'm sorry, I don't understand your question. Could you try to restate it?

**Comment by jeffersongouveia** [comment]
I have this line that defines the start time and works
```javascript
$('#start_time').timepicker('setTime', date.format('hh:mm'));
```

So i did the same for the end time
```javascript
$('#end_time').timepicker('setTime', end_time);
```

And it sets, but not the right way
![datepair](https://cloud.githubusercontent.com/assets/12664845/11033903/86ced0b8-86bd-11e5-8a95-947ff7299aa7.png)

What I need? This
![datepair-two](https://cloud.githubusercontent.com/assets/12664845/11034093/20373f00-86bf-11e5-9984-854fd21b0f7c.png)

**Comment by jonthornton** [comment]
You probably need to call Datepair's `refresh()` method after setting the end time. From the readme:

> Call this method if you programmatically update the date/time fields after first initialization of datepair.
