### ISSUE TITLE
Datepair.js, bootstrap and Rails

### ISSUE THREAD

**Issue by wasafiri** [jonthornton/Datepair.js#66]
There is an incompatibility with the Datepair.js and the bootstrap.datepicker.

The bootstrap API now only offers a .datetimepicker() function which is cool, but Datepair does not work well with it. Also I tried using the older versions of the libraries which do work, but they are incompatible with the newer bootstrap.

**Comment by jonthornton** [comment]
Can you point me to the docs for that plugin? [bootstrap-datepicker's docs](https://bootstrap-datepicker.readthedocs.org/en/latest/) don't mention a `.datetimepicker()` method.

**Comment by wasafiri** [comment]
In the minimum set up example: https://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by jonthornton** [comment]
`bootstrap-datetimepicker` != `bootstrap-datepicker`. The projects have different maintainers and appear to be unrelated. Datepair.js is designed to work with the plugin found here: https://github.com/eternicode/bootstrap-datepicker
