### ISSUE TITLE
Time picker not working properly. 

### ISSUE THREAD

**Issue by swapnilchinchwade** [jonthornton/Datepair.js#68]
Selecting end time and again selecting start time does not reflect to end time of 1 hour difference.

**Comment by jonthornton** [comment]
I don't understand. Can you provide an example and step by step instructions to reproduce the problem?

**Comment by swapnilchinchwade** [comment]
If you choose start time 9AM it will set end time to 10AM ,
After doing this if you again change end time and then start time the
result of end time of should be one hour difference, which is not
displaying correct value.

**Comment by robjens** [comment]
I should have filed a ticket when I was experiencing these problems but figured out for the most of it, with me, it seems it only likes `id` from the main, one and only container. Any paired field moves to another div? Bust. Any nested selector? Bust. Anything that went beyond the examples really, found it extremely hard to get it working properly. So I'd say, try and start with keeping all the time fields inside 1 div only and reference that by id in the jquery selector (if you use that) and ensure all the dependencies are loaded in the right order. At least that's where I started troubleshooting each time (and as I said, there were plenty, wouldn't have taken long or I would have dropped this library if I didn't solve it then).

Anyway, @swapnilchinchwade I'd say begin by sharing which config you are using? Simple, jQuery? Bootstrap? Show some code how you initialize and markup please.

**Comment by robjens** [comment]
@jonthornton Maybe the documentation/examples need some work though. For example, the jQuery time only pair example shows you first using a `$` jQuery selector, then you use a native DOM accessor `document.getElementById()` then you assign a variable to something (`new Datepair(ele)`) which isn't used or anything. Assume this patches the fields? Why the need for the object instance? Anyway I haven't had much time to dive in the source (I'll probably do so in a few) so nothing concrete to suggest or PR in that respect but if I do find out where confusion is coming from, I'll be sure to let you know. Trying to get this puppy to work (again)
