### ISSUE TITLE
Selectable only from 0:00 to 24:00

### ISSUE THREAD

**Issue by Inselhopper** [jonthornton/Datepair.js#70]
How set the picker selectable from 0:00 to 24:00? ('step': 15)

'minTime': '0:00',
'maxTime': '24:00',

does not work. 

Thanks for your work!

**Comment by jonthornton** [comment]
The timepicker is a separate project. Documentation can be found at https://github.com/jonthornton/jquery-timepicker

```javascript
$('#someTimeInput').timepicker({
  'timeFormat': 'G:i',
  'show2400': true
});
```
