### ISSUE TITLE
when value set on both dateinputs, the second dateinput doesn't change when second timeinput is set after midnight

### ISSUE THREAD

**Issue by pixeldoris** [jonthornton/Datepair.js#73]
I have this problem with an application. I need to be able to alter the time-span of an already existing work shift in a certain event and the date needs to be altered automatically depending on the time.

I have this form which is automatically filled in with data from a database.

    <input type="hidden" class="date start" value=" $startdate "> // 2016-05-18
    <input type="text" class="time start" value=" $starttime "> // 18:00
    <input type="hidden" class="date end" value=" $enddate"> // 2016-05-18
    <input type="text" class="time end" value=" $endtime "> // 23:00

The problem is that when I set the $endtime input to, for example, 03:00 after midnight. The $starttime is set to 03.00 too instead of the $enddate changing to '2016-05-19'.

Is this fixable or do I need to go the extra mile and code something like:

    $start = strtotime($starttime);
    $end = strtotime($endtime);
    $midnight = strtotime('00:00');

    if ($end < $start AND $end > $midnight) {
        // Add one day to $enddate
    } 

 and skip the date inputs etc....

**Comment by jonthornton** [comment]
The end date should roll over automatically, and the start time should not change. Can you post a link that demonstrates the problem?

**Comment by pixeldoris** [comment]
I can't post the actual link since it's "the real deal" but maybe I can make a fiddle (never done it but I'll try) and if the fiddle works I might just have some code that's colliding with datepair. But I'll try to make a fiddle now..

**Comment by pixeldoris** [comment]
I just realize I can't include the datepair since it's a file and not an CDN..

**Comment by pixeldoris** [comment]
I can't get the fiddle to even work with the datepicker, timepicker.. but I did go the extra mile, so my application does work, but extra code is never nice.. :/ to bad I can't demonstrate my problem.

**Comment by jonthornton** [comment]
Try this as a starting point for the fiddle http://jsfiddle.net/jonthornton/dx8xkvnb/

**Comment by pixeldoris** [comment]
When I alter that one so that it has the same code as the website I'm working on it's working just fine.. I have no idea what's causing this bug on my page, but atleast now I know it's not the datepair..

**Comment by pixeldoris** [comment]
I have a videoclip when I'm demostrating, can I send it somewhere? so that you'll see?

**Comment by jonthornton** [comment]
Isolating the problem in a jsfiddle is the only way I can help. It's impossible to debug without code.

**Comment by pixeldoris** [comment]
http://sbssakerhet.se/login/help.php I created an extra file with just the form that doesn't exist.

When you don't alter the date, it doesn't work. if you alter the date, it works as it should.

**Comment by pixeldoris** [comment]
it's so weird suddenly it works...

**Comment by pixeldoris** [comment]
I think I know when it doesn't work.. it's when I have a date that's already passed, since I don't allow to pick those dates it can't choose that... now it all makes sense.

**Comment by jonthornton** [comment]
https://en.wikipedia.org/wiki/Rubber_duck_debugging :)
