### ISSUE TITLE
bootstrap-datepicker changeDate event not firing when maintaining duration

### ISSUE THREAD

**Issue by gregegan** [jonthornton/Datepair.js#78]
https://bootstrap-datepicker.readthedocs.io/en/stable/events.html#changedate 

It seems like when datepair automatically adjusts the endDate to maintain the duration from a startDate change, a `changeDate` event never fires.

`this.$dateEnd.on('changeDate', () => { console.log('end date changed'); });`

**Comment by gregegan** [comment]
Actually... it looks like `rangeSelected` can handle this for me rather then a listener on each date/time component

`this.$dateRangeContainer.on('rangeSelected', () => { debugger;  });`

**Comment by jonthornton** [comment]
Yep, that'll work. You could also do `this.$dateRangeContainer.on('changeDate', () => { debugger; });` to capture events from both the start and end inputs.

**Comment by gregegan** [comment]
👍
