### ISSUE TITLE
Invalid time values.Require to allow only numbers

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [jonthornton/Datepair.js#79]
Hi,
I have a requirement where in time-picker(jquery),only numbers are allowed.
But look at image attached which is doing nothing when something strange is passed.

![screenshot 121](https://cloud.githubusercontent.com/assets/16798757/17783986/48469f00-6598-11e6-87a0-b0a9b9c86ab4.png)

Also,I am unable to produce any triggering for "rangeError"

**Comment by jonthornton** [comment]
That situation will trigger a `rangeIncomplete` event, because the invalid times are treated as `null`s.

**Comment by avinashramireddy-rapidd** [comment]
After typing I moved my cursor out of focus. But  when you see the image it's showing as valid range selected instead of `rangeIncomplete`.

Am I wrong?
If it's a feature then I need to empty it,instead of showing that kind of letters.How can I do that?
