### ISSUE TITLE
Manually entering time and pressing enter rounding the time

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [jonthornton/Datepair.js#87]
Hi,
Manually entering time in time field and pressing enter rounding the time to nearest value from dropdown. But when I enter the same time and press TAB  it holds entered value.
I am going to change in script file of jquery-timepicker by debugging.
But is there any way to do this without doing any changes to the code by some kind  of settings?

**Comment by jonthornton** [comment]
You're referring to something specific to jquery-timepicker. This is the intended behavior. Hitting enter grabs the selected value from the dropdown.

Disable automatic highlighting by setting `typeaheadHighlight: false` in the timepicker options.
