### ISSUE TITLE
rangeIncomplete event fires when a date is first set in the anchor input

### ISSUE THREAD

**Issue by jkallay1** [jonthornton/Datepair.js#95]
If the anchor is the start input:
When a value is set in the start input for the first time, in line 267 of datepair.js the newTime variable is successfully initialized but this.timeDelta is null, and won't be set to a non-null value. Thus when _validateRanges is called the null test of this.timeDelta will cause the rangeIncomplete event to fire. I think the fix is to set a non-null value to this.timeDelta before initializing newTime.

**Comment by jonthornton** [comment]
This only happens when `defaultTimeDelta` is set to null. The point of `defaultTimeDelta` is to solve exactly this problem, and it defaults to 1 hour. Please provide a code sample if you're still experiencing problems.

**Comment by jkallay1** [comment]
Sorry, I completely botched the original bug description. I had to reread it myself about a dozen times to figure out what I had been talking about. As you noted, the issue occurs when defaultTimeDelta is null. But the information I left out is that the follower (non-anchor) input has a time set on it first. The rangeIncomplete event fires. Then, when a time is set on the anchor, the rangeIncomplete anchor fires again (even though the range isn't incomplete).
See this jsFiddle: https://jsfiddle.net/ez7khL74/
