### ISSUE TITLE
rangeSelected event should fire after clearing both time pickers

### ISSUE THREAD

**Issue by jkallay1** [jonthornton/Datepair.js#97]
See #96.
An empty range is semantically more closely related to a complete range selection than it is to an incomplete range selection.
With this change it would be appropriate to rename the event to, for example, "rangeSelectionChanged."

**Comment by jonthornton** [comment]
`rangeSelectionChanged` could be deduced by listening for `change` events from any of the inputs that make up the range selection UI - you don't need datepair to fire that event.

**Comment by jkallay1** [comment]
The argument that an end could be achieved by working with the lower level components seems odd. What is datepair.js for, if it can't be treated as a logical wrapper around the selection (or, in this case, non-selection) of a time range that obviates having to manually interrogate the individual components?
